### ISSUE TITLE
[Task]: Improve Tooltip component 

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#1015]
### Task description

Improve the generic `Tooltip` component to have the following aspects:

- [ ] Add a custom hook that can give us dynamic cursor coordinates
- [ ] Tooltip position is dynamic based on cursor position
- [ ] Tooltip respects the "window edges", and doesn't go outside the screen or under another element
- [ ] (Optionally) Improve support for overriding "tooltip content" styles

tip: Look into `ChartTooltip` for logic of "following the cursor" or "window edges awareness"
