### ISSUE TITLE
[Task]: Add accounts stats to landing page

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1056]
### Task description

- [ ] Number of total accounts
- [ ] Number of total active validators
- [ ] Number of total active delegatos
