### ISSUE TITLE
[Task]: Add controls feature to tweak the visualizer easier

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1171]
### Task description

Comms would like to be able to tweak the visualizer so they study the sweet config to have a nice looking visualizer.
We should be able to configure showing or not the controls box.
The controls box is intended to be not fancy at all, just exposing some inputs so comms can tweak parameters. The controsls should initialize with the values we have configured by default. On every input change (except for zoom), the visualizer should reset and start again

List of configurable parameters:
- [ ] Min sinusoid amplitude
- [ ] Max sinusoid amplitude
- [ ] Min sinousoid period
- [ ] Max sinousoid period
- [ ] Max tilt degrees
- [ ] Min tilt degress
- [ ] Min tilt period ( 2 times TILT_DURATION_SECONDS )
- [ ] Max tilt period ( 2 times TILT_DURATION_SECONDS )
- [ ] Zoom
