### ISSUE TITLE
[Task]: Polish visualizer

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1277]
### Task description

- [ ] Update background colors to be like the prev threejs visualizer
- [ ] Increase a bit the block sizes
- [ ] Soften the connections a bit so they are not too bright
- [ ] In highligthing colors, soften the colors too so its not so bright
