### ISSUE TITLE
[Task]: Polish Output page

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1305]
### Task description

- [x] Add mana units to all output mana values
- [x] Add to metadata "Commitment ID" --> `metadata.included.commitmentID` with a link to the right slot (you have in the metadata the slot index too)
- [x] Add link to validator address
- [x] Add link to epoch (unless `0`)
- [x] Add hint to end epoch when its `0` explaining what it means: "When end epoch is 0 it means there is no end epoch defined for this delegation output" (ask chatgpt for a better explanation lol)
- [x] Always display mana, except for the delegation rewards mana which should be displayed only in delegation outputs (but always displayed even when 0)
- [x] Add units to staked amount
- [x] what is `Fixed cost`? Can we explain this number a bit better like..is it a percentage so we should add `%`?
