### ISSUE TITLE
[Task]: Finalize & polish landing current epoch

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1306]
### Task description

**Finalize landing epoch section: add real values:**
- [ ] validators
- [ ] staked in active set
- [ ] delegated in active set

**Polish landing epoch:**
- [ ] time remaining: add time units h,m,s
- [ ] add button urls
- [ ] from -> to with the same time accuracy as the epoch page (missing h:m:s)
