### ISSUE TITLE
[Task]: Add sdk dependency to use official npm package

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1326]
### Task description

- [ ] Update dependency to use https://github.com/iotaledger/iota-sdk/releases/tag/iota-sdk-nodejs-v2.0.0-alpha.1
- [ ] Update CI to remove sdk build
- [ ] Cleanup es-lint ignores

**Comment by VmMad** [comment]
Let's wait until we get the release for @iota/sdk-wasm to use in the client

**Comment by begonaalvarezd** [comment]
Unblocked https://github.com/iotaledger/iota-sdk/releases/tag/iota-sdk-wasm-v2.0.0-alpha.1
