### ISSUE TITLE
[Task]: Polish epoch page

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1354]
### Task description

- [x] Add hhmmss to time remaining
- [x] Add units to total pool stake, total validator stake, total delegated stake
- [x] Use reusable table component for the Committee & Candidates tables
   - add units to all stakes
   - add units to cost
   - allow copy validator address
   - link to address
