### ISSUE TITLE
[Task]: Polish validators page

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1356]
### Task description

- [ ] Use reusable table component
- [ ] Copy address
- [ ] Link to address
- [ ] Add units to cost, stakes and pools
- [ ] Hide delegators
