### ISSUE TITLE
[Task]: Polish mobile UI pages

### ISSUE THREAD

**Issue by panteleymonchuk** [iotaledger/explorer#1391]
### Task description

Improve UI for some pages:

- [ ] Epoch page has wrong paddings.
- [ ] Improve KeyPanel for Visualizer
- [ ] Output page. Number near “delegation” is out of screen.

### Screens

![image](https://github.com/iotaledger/explorer/assets/25872497/6ce68130-8213-4df8-a1ae-19e64bfaeb90)
![image](https://github.com/iotaledger/explorer/assets/25872497/bfa55373-e6f1-47cd-8bed-e0700ab349e4)
![image](https://github.com/iotaledger/explorer/assets/25872497/419365e1-6ec3-412a-b101-e991be5d664a)
