### ISSUE TITLE
[Task]: Polish address page delegation & validation tabs

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1458]
### Task description

- [ ] Use boxes for delegated amount and rewards
![image](https://github.com/iotaledger/explorer/assets/3624944/851695b4-fcf1-4722-8645-b59f3905ecee)
![image](https://github.com/iotaledger/explorer/assets/3624944/189b2eef-e166-4605-9f89-130f6971e6be)
- [ ] Add units to delegated amount & rewards (with click to toggle)
- [ ] Replace "Output Id" with "Delegations" in the validation tab 
![image](https://github.com/iotaledger/explorer/assets/3624944/d806d90d-8822-4189-b9b5-36c9ad3ad09b)
