### ISSUE TITLE
[Task]: Add Output Page 

### ISSUE THREAD

**Issue by lzpap** [iotaledger/explorer#370]
### Task description

Each individual protocol component should have its dedicated page on the explorer.
 - **output**: clicking on an output Id should display the content of the actual output + its metadata.
 - **transaction**: clicking on a transaction Id should display the transaction with its content and metadata https://github.com/iotaledger/explorer/issues/329
 - **block**: clicking on a block Id should display the content of the block + metadata. Already supported.

Current task is about adding an output page.
 - [ ] Display the content of the output. Can reuse the output object that is currently displayed inside transactions, but expand all fields by default.
 - [ ] Take care to differentiate between`Features` and `Immutable Features`. A `Metadata Feature` for example may be present in both.
 - [ ] Display metadata of an output returned by the core api:

Unspent Output Metadata:
```json
    "metadata": {
        "blockId": "0xfa552b5047cf1521766b617e578f587e104092fa8a9f3bc05682f4b7ed184905",
        "transactionId": "0xde27b579159390beb1aa4fbf1eb7f623ccba7f010bf93999ad69f29bc065409d",
        "outputIndex": 2,
        "isSpent": false,
        "milestoneIndexBooked": 4249,
        "milestoneTimestampBooked": 1655898244,
        "ledgerIndex": 91519
    },
```
Spent Output Metadata:
```json
    "metadata": {
        "blockId": "0xf481646c9009d1df0d508ebd0ab7629f7ed41de13625933abd1945e55eade949",
        "transactionId": "0x21351774ee4b16027677fcc1b120a9ec7807bb07cda29eedd081675787c968c8",
        "outputIndex": 0,
        "isSpent": true,
        "milestoneIndexSpent": 4249,
        "milestoneTimestampSpent": 1655898244,
        "transactionIdSpent": "0xde27b579159390beb1aa4fbf1eb7f623ccba7f010bf93999ad69f29bc065409d",
        "milestoneIndexBooked": 4249,
        "milestoneTimestampBooked": 1655898244,
        "ledgerIndex": 91544
    },
```
 

### Requirements

-

### Acceptance criteria

-

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
