### ISSUE TITLE
[Epic]: Explorer UI/UX improvements

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#570]
### Task description

Placeholder for UI/UX improvements tasks: 

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/explorer/issues/599
- [ ] https://github.com/iotaledger/explorer/issues/586
- [ ] https://github.com/iotaledger/explorer/issues/495
```

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
