### ISSUE TITLE
[Draft]: Highlight genesis Block ID

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#578]
### Task description

As a user, I want to have special IDs highlighted (like genesis block ID for instance), so that i can more easily recognize what that means.

- [ ] Highlight genesis BlockId

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
