### ISSUE TITLE
[Draft]: Tabify the sections on Address page

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#586]
### Task description

Address page is getting too long, we should divide the section to tabs.

- [ ] Build generic components for "tabifying pages"
- [ ] If there are sections which are not extracted to own-component, extract them
- [ ] Add tabs under General section so that all other sections are "tabbed"

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
