### ISSUE TITLE
[Task]: Build the Statistics page UI

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#593]
### Task description

Build the UI for Statistics page leveraging `d3`, data from InfluxDB and inspiration from **[figma](https://www.figma.com/file/j4RLa61iZ18VXwiabeyu9k/IOTA-Explorer-UI?node-id=3374%3A49095)**

- [x] Support chart types as the graphs on Graphana
- [x] Add single value metrics to statistics page (with generic component)

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
