### ISSUE TITLE
[Task]: Adapt designs of Statistics page

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#600]
### Task description

- [ ] Update UI of Statistics page to match latest [figma](https://www.figma.com/file/j4RLa61iZ18VXwiabeyu9k/IOTA-Explorer-UI?node-id=3621%3A49463)

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
