### ISSUE TITLE
[Task]: Finalize Statistics page

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#601]
### Task description

Remaining issues:
- [x] Add error handling to page (if the data doesn't load/empty show graph placeholders with "No data" label)
- [x] Add tooltip on hover to area that takes the "closest" point for data context (optionally)
- [x] Improve x-axis ticks label visibility across timespans
- [x] Hide the dots on StackedLineChart (but tooltip still shows the data on hover)
- [x] Improve timespan dropdown
- [x] Page responsiveness

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
