### ISSUE TITLE
[Task]: Pre-load Landing page

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#602]
### Task description

As i user i want to see the landing page already populated with data when i navigate to it.

- [ ] Cache the last 10 "milestones data" (check `baseStatsService`, there is already a milestoneCache there that can be used)
- [ ] Show cached entries when user lands on landing page. On Landing (stardust) we can hook up a call in `ComponentDidMount` to fetch the cached entries.

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
