### ISSUE TITLE
[Task]: Fix the locked storage deposit stat query (Statistics page)

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#627]
### Task description

~~The data in the locked storage deposit graph needs to be computed the same way like the lockedStorageDeposit analytic statistic.~~

- ~~Update the query here https://github.com/iotaledger/explorer/blob/dev/api/src/services/stardust/influx/influxQueries.ts~~
- ~~Add logic to compute the correct value for each day (like we did for the Locked storage deposit stat) in influxClient https://github.com/iotaledger/explorer/blob/480c6eeadf9bee2f57ebc1821e823b9b4ceecfc5/api/src/services/stardust/influx/influxDbClient.ts#L327~~

~~Check with @grtlr if graph with new computed data makes sense.~~

EDIT:

The graph daily query is correct now. So we need to
- [x] Remove the computation that account for byte cost from the Locked storage stat, and just simply take the query result. 

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by msarcev** [comment]
### Scope change
Meanwhile the Chronicle team actually updated the computation on their side.
So that now we don't need to "account for byte cost" and compute the right value from two different queries.
This task scope changes from "Fixing the LockedStorageDeposit graph to also compute the right value for each day entry"
to
"Simplify the query for the LockedStorageDeposit statistic to just take the value from **one** query, and remove additional computation" (the graph query is already good, no changes needed)
