### ISSUE TITLE
[Task]: Add info tooltips on Statistics page

### ISSUE THREAD

**Issue by lzpap** [iotaledger/explorer#628]
### Task description

Add informative description tooltips for charts on the [statistics page](https://explorer.iota.org/shimmer/statistics/) that help the reader understand iota/shimmer specific concepts and the metrics themselves.

Examples:
 - _Unlock Conditions: Configurable scripts attached to funds that govern who, how and when can access those._
 - _Daily Active Addresses: Addresses that appear in confirmed transactions on a given date._

The tooltips may point to the wiki for more information.

### Requirements

Each section head, graph title and technical term appearing throughout the statistics page displays an informative tooltip when hoverd over by mouse.

### Acceptance criteria

- [ ] Tooltips displayed on all technical terms on the statistics page.
- [ ] Wording reviewed by non-technical people as well for readability.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
