### ISSUE TITLE
[Task]: Finalise the NFT/NativeTokens metadata feature branch

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#679]
### Task description

```[tasklist]
### Tasks
- [x] Not whitelisted message make it "NFT Schema Standard is IRC27. Please consider submitting an entry to the [Token Registry.](https://github.com/iota-community/token-whitelist)"
- [x] Replace the image placeholder with some components so we can control the text
- [ ] https://github.com/iotaledger/explorer/pull/684
- [x] Allow for NFT standard field "attributes" to also be an object (ignore it in the validation)
- [x] Improve the attributes section (see comment)
- [x] Check pages on "dark mode"
- [x] Group Address Sections into an "address" folder under components/stardust https://github.com/iotaledger/explorer/pull/698
- [x] Error thrown if nft metadata feature is undefined on NftSection
- [ ] https://github.com/iotaledger/explorer/issues/687
- [x] Remove http-ipfs-client lib and add minimal ipfs client https://github.com/iotaledger/explorer/pull/695
- [x] Add loader for fetching nft metadata uri https://github.com/iotaledger/explorer/pull/695
- [x] Nft names on NftSection are not resetting when navigating trough pages
- [x] Remove all files/code related to endpoint `stardustTangleCacheService#nftRegistryDetails`
- [x] Check what we can do to make images with weird aspect ratios look better
- [x] Do a thorough code review of the feature branch
- [x] Bump version of Explorer to v3.1.0
```

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by msarcev** [comment]
![image](https://user-images.githubusercontent.com/6864498/220711873-3d7fc115-c1d8-486b-9bfc-7aa2fb24d279.png)
The attributes section looks weird with the scroll in the middle
