### ISSUE TITLE
[Task]: Differentiate between Tangle and Ledger

### ISSUE THREAD

**Issue by adrian-grassl** [iotaledger/explorer#686]
### Task description

The wording in the block metadata is misleading. The Tangle consists of Blocks, the Ledger consists of UTXOs. Therefore a block can't be part of the ledger.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/83593889/220386021-50aa54a9-1b0c-478a-abdb-d84b9bf3b519.png">

### Requirements

**Topic Proposal**
The point should be something like `Block Confirmation Status` instead of `Ledger Inclusion`.

**Description Proposal:**
Transaction Payload: `The block is confirmed by a milestone and the transaction successfully mutated the ledger state.`
Data Payload: `The block is confirmed by a milestone.`

### Acceptance criteria

Clarity between Blocks in the Tangle and Outputs in the Ledger.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by msarcev** [comment]
- [ ] Change header to `Confirmation Status`
- [ ] For transactionPayload blocks, if `ledgerInclusionState` is confirmed, `The block is confirmed by a milestone and the transaction successfully mutated the ledger state.`
- [ ] For transactionPayload blocks, if `ledgerInclusionState` is conflicting, `The block is confirmed by a milestone but the transaction is conflicting.`
- [ ] Also for `noTransaction` inclusion state remove the `, the data is included in the ledger` part.

**Comment by adrian-grassl** [comment]
Do we actually call Blocks "confirmed" when they contain an invalid transaction? To me the confirmation state only makes sense on the transaction payload level. On block level I would stick to "inclusion" state (to the Tangle).

A) Your Tx was included to the Tangle and confirmed
B) Your Tx was included to the Tangle, but conflicting

**Comment by msarcev** [comment]
Changed the header to `Inclusion Status`
