### ISSUE TITLE
[Epic]: Explorer GoShimmer/Protonet integration

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#711]
### Task description

This epic mainly describes the tasks to be done for completing the support of the GoShimmer MVP/protonet protocol version.

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/explorer/issues/767
- [ ] https://github.com/iotaledger/explorer/issues/768
- [ ] https://github.com/iotaledger/explorer/issues/769
- [ ] https://github.com/iotaledger/explorer/issues/770
- [ ] Adjust `protonet` explorer skinning to new designs
- [ ] Adjust `protonet` visualizer to the new design
```

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
@msarcev do we still need this task?
