### ISSUE TITLE
[Task]: Add a redirect from old NFT route to NFT Address page

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#714]
### Task description

The NFT `/nft/` route was removed with https://github.com/iotaledger/explorer/pull/643 to unify the address pages. But there are still external links pointing to that route.

- [ ] Add a redirect for the route (also supporting hex ID), to the address route with `bech32` address format. 

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
