### ISSUE TITLE
[Task]: Add a view for richest addresses to Statistics page

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#721]
### Task description

- [x] Tabify the statistics so that the current content is under a "Chart" tab
- [x] Add a "Token Distribution" tab with two sections. Top one is token distribution data, bottom is richest addresses
- [ ] Render the token dist data in a pie chart with d3.js
- [x] Show the top 100 richest addresses

Cache the data periodically on backend, return to client the latest data from cache.

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
