### ISSUE TITLE
[Task]: Improvements for Statistics (Charts) page

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#752]
### Task description

- [x] Make the first two graphs also StackedLineChart
- [x] Fix the labels to not be days but months on (all time)
- [x] Revise colours of Y axis in dark mode (hard to distinguish)
- [x] Revise formatting for large numbers in tooltips (format to magnitudes, hide decimals)
- [x] Add zooming support to charts
- [x] Remove the timespan selector as it's redundant now that is possible to zoom

Resolves https://github.com/iotaledger/explorer/issues/740
Resolves https://github.com/iotaledger/explorer/issues/742

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by msarcev** [comment]
Check open external issues about this:
https://github.com/iotaledger/explorer/issues/742
https://github.com/iotaledger/explorer/issues/740
