### ISSUE TITLE
[Epic]: Implement Visualiser with ThreeJS (stardust)

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#782]
### Task description

Epic for tracking progress with Visualizer with ThreeJS
**Sub-tasks should be closed through PRs.**

```[tasklist]
### Tasks
- [x] (Refactor) Improve naming of `EmitterProps`. These come from `useUpdateListener` returns, but the naming is a bit cryptic. I suggest `[updateListenerConnected, setUpdateListenerConnected]`. Optionally add other refactor improvements you notice.
- [x] (Feat) Implement (re-connect) the pause button. On pause renderer should stop and `useUpdateListener` should stop listening for new blocks.
- [x] (Fix) Improve behaviour when changing tabs. Current plan is to stop the stream (pause) and have it paused when you come back to tab.
- [x] (Feat) Implement a BPS tracker to be able to track the tangle speed reliably
- [x] (Fix) Improve zooming logic (from 5BPS to 100+BPS) and emitter position consistency with different zoom values.
- [x] (Feat) Performance optimization placeholder: Do some profiling + Try to render nodes directly to scene + Webworker if needed
- [x] Investigate how to implement listeners for block onClick, onHover etc...
- [x] Investigate options to have another instancedMesh with the block connections (lines)
- [ ] Investigate how we can control 'CameraControls' (like limit the zoom out/in, rotate etc...)
```

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
