### ISSUE TITLE
[Task]: Disable tools and feed on legacy-mainnet (archive network)

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#856]
### Task description

- [x] Remove message/tx feed from landing page
- [x] Remove visualizer & statistics from navbar
- [x] Remove (if super easy, otherwise ignore) the landing quick stats: tx/s & inclusion rate
### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
