### ISSUE TITLE
[Task Tracker]: Add Nova service (api)

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#861]
### Task description

- [ ] [Task]: Add Nova service: Node Info
- [ ] [Task]: Add Nova service: Feed (mqtt)
- [ ] [Task]: Add Nova service: Client

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
