### ISSUE TITLE
[Task]: Support Basic Output

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#865]
### Task description

- [ ] TIP updates: eg, native tokens is not array anymore
- [ ] Add basic output page (client)
- [ ] Add outputDetails to NovaApiClient 
- [ ] Add custom hook to fetch the output (client)
- [ ] Add getter route to api
- [ ] Add outputDetails to NovaTangleHelper
- [ ] Add IOutputDetailsResponse to models (api)

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
