### ISSUE TITLE
[Task Tracker]: Support Block Page

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#882]
### Task description

- [x] No payload
- [x] Tagged data payload
- [x] Transaction Payload

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/explorer/issues/958
- [ ] https://github.com/iotaledger/explorer/issues/972
- [ ] https://github.com/iotaledger/explorer/issues/973
- [ ] https://github.com/iotaledger/explorer/issues/974
- [ ] https://github.com/iotaledger/explorer/issues/975
```

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
