### ISSUE TITLE
[Task]: Support address page: Account

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#885]
### Task description

TODO
- [x] Address page basic infra
- [x] Associated outputs section

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
