### ISSUE TITLE
[Task]: Update visualizer models to nova

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#896]
### Task description

- [ ] in `client/src/features/visualizer-threejs/wrapper/SelectedFeedInfo.tsx` we still use the stardust wasm, we should point to the nova one and update conflicting to failed reasons
- [ ] update `client/src/features/visualizer-threejs/types.ts` to use nova models instead
- [ ] update `client/src/features/visualizer-threejs/VisualizerInstance.tsx` to use nova models instead
- [ ] update `client/src/features/visualizer-threejs/store/tangle.ts` to use nova models instead
- [ ] update `client/src/features/visualizer-threejs/wrapper/SelectedFeedInfo.tsx` to use nova models instead
- [ ] update `client/src/features/visualizer-threejs/wrapper/StatsPanel.tsx` to use nova models instead

⚠️ If some of these points escalates, please notify so we split this task into multiple, `client/src/helpers/stardust/hooks/useNetworkStats.ts` might need some discussion in case its not yet available or something
