### ISSUE TITLE
[Task Tracker]: Improve visualizer topology/design 

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#902]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/explorer/issues/903
- [ ] https://github.com/iotaledger/explorer/issues/904
- [ ] https://github.com/iotaledger/explorer/issues/905
- [ ] #893
- [ ] #892
- [ ] #891
- [ ] https://github.com/iotaledger/explorer/issues/906
- [ ] https://github.com/iotaledger/explorer/issues/907
- [ ] https://github.com/iotaledger/explorer/issues/908
```
