### ISSUE TITLE
[Task]: Fix supply increase stardust genesis outputs marked as chrysalis

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#917]
### Task description

On the supply increase (the merge on October 4 2023), outputs with a specific marker were added to genesis

```
export const VESTING_OUTPUT_SUPPLY_MARKER = '0xb191c4bc825ac6983789e50545d5ef07a1d293a98ad974fc9498cb18'
```

It looks like the explorer derives the tx id from the outputs, and its marking these transactions as chrysalis, when they actually are "Mainnet Stardust Genesis" and should link nowhere because there is no tx in genesis

Examples:

- https://explorer.iota.org/mainnet/addr/iota1qplg75xh5q7j4wrly83d06wqws20rsddye537et277zqm53vt707y5tv3zg?tab=Transactions
- http://localhost:3000/mainnet/output/0xb191c4bc825ac6983789e50545d5ef07a1d293a98ad974fc9498cb18822c13000000

We should fix
- [ ] transaction history part in address page
- [ ] output page: there is no tx associated to these genesis outputs

⚠ Lets not remove the current chrysalis-mainnet logic thing, this issue is just about covering the supply increase marker

### Requirements

Supply increase outputs fixed

### Acceptance criteria

Supply increase outputs fixed

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
