### ISSUE TITLE
[Task]: Remove identity resolver utility from stardust networks

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#918]
### Task description

After this PR https://github.com/iotaledger/explorer/pull/852 we dont need the identity resolver utility anymore in stardust networks, so it can be removed

### Requirements

- [ ] Remove identity resolver from stardust
- [ ] Cleanup all debris

![image](https://github.com/iotaledger/explorer/assets/3624944/a615a6af-f8d9-4f86-9f8a-905eec6af820)

### Acceptance criteria

Above mentioned

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
