### ISSUE TITLE
[Task]: Add prettier config

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#934]
### Task description

lets try to keep the config as the code is written now, if needed we can update it in the future but now lets keep it simple

- [ ] Add prettier config to minimize changes in current code
- [ ] Format whole codebase

### Requirements

Above mentioned

### Acceptance criteria

Above mentioned

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
