### ISSUE TITLE
[Task Tracker]: Extend Output

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#946]
### Task description

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/explorer/issues/952
- [ ] https://github.com/iotaledger/explorer/issues/953
- [ ] https://github.com/iotaledger/explorer/issues/954
- [ ] https://github.com/iotaledger/explorer/issues/955
- [ ] https://github.com/iotaledger/explorer/issues/956
- [ ] https://github.com/iotaledger/explorer/issues/957
```

Top level fields for ALL the outputs
eg:
- Basic Output: mana
- Account output: mana, account id, foundry counter
- .... 

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
