### ISSUE TITLE
[Task]: Polish the Block page

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#994]
### Task description
- [x] Fix issuer link to be address url
- [x] Rename `Creation slot` to `Transaction creation slot`
- [x] Link Slot commitment to the slot page
- [x] "Highest supported protocol version" not in blue
