### ISSUE TITLE
[Task Tracker]: Add mana to the output page

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#998]
Add mana to the output page:

- Total = stored + potential + (delegation rewards)
    - stored mana: display decayed value & literal stored mana
    - potential mana: the value given to us should be already decayed
    - delegation rewards (if delegation output): the value given to us should be already decayed (for now we forget about chronicle and asume we can get the delegation rewards from the nodes)

📓 Notes:
- Both spent and unspent outputs should contain the above values
- For the unspent outputs, all the mana values should be displayed relative to now
- For the spent outputs, all the mana values should be displayed relative to when it was spent

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/explorer/issues/999
- [ ] https://github.com/iotaledger/explorer/issues/1000
- [ ] https://github.com/iotaledger/explorer/issues/1001
```
